# -*- Mode: makefile-gmake; tab-width: 4; indent-tabs-mode: t -*-

ifeq ($(origin SRC_ROOT),undefined)
SRC_ROOT=$(dir $(realpath $(firstword $(MAKEFILE_LIST))))../../..
endif

include $(SRC_ROOT)/solenv/gbuild/partial_build.mk

# vim: set noet sw=4 ts=4:
