# Configuration for Repo Lockdown - https://github.com/dessant/repo-lockdown
# LibreOffice project uses gerrit as its patch management & review system
name: Repo Lockdown

on:
  issues:
    types: opened
  pull_request_target:
    types: opened

jobs:
  point-to-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2.2.0
        with:
          issue-comment: >
            Thank you for your report. We use GitHub as a read-only mirror, so please submit your report into our own bug tracker: https://wiki.documentfoundation.org/QA/BugReport
          skip-closed-issue-comment: true
          close-issue: true
          lock-issue: false
          pr-comment: >
            Thank you for your contribution. We use GitHub as a read-only mirror. Translations are maintained in weblate, see https://wiki.documentfoundation.org/Translating_LibreOffice for details on how to contribute.
          skip-closed-pr-comment: true
          close-pr: true
          lock-pr: false
